version: '3'

services:
    app:
        build: .
        container_name: cplug_app
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USERNAME=cplug
            - DB_DATABASE=cplug
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
    db:
        image: mariadb:10.11.3
        container_name: cplug_db
        ports:
            - 33068:3306
        volumes:
            - .db/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: cplug
            MYSQL_USER: cplug
            MYSQL_PASSWORD: cplug
            MYSQL_ROOT_PASSWORD: cplug

